name: CI
# 当有改动推送到master分支时，启动Action
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: main

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
          
      - name: Install Pandoc
        run: |
          curl -s -L https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-linux-amd64.tar.gz | tar xvzf - -C $RUNNER_TOOL_CACHE/
     
      - name: 缓存 Hexo
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # - name: 安装依赖
      #   if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      #   run: |
      #     npm install gulp-cli -g #全局安装gulp
      #     npm install --save

      - name: 生成静态文件
        run: |
          export PATH="$PATH:$RUNNER_TOOL_CACHE/pandoc-2.9.2/bin"
          hexo clean
          hexo generate
          # gulp

      - name: 部署到Github
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.HEXO_TOKEN }}
          repository-name: qinwant/kingwan.github.io
          branch: main
          folder: public
          # commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"
